# Generated by Django 4.2.17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pretix_servicefees", "0002_tax_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemservicefeessettings",
            name="fee_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=13,
                null=True,
                verbose_name="Fee (amount)",
            ),
        ),
        migrations.AddField(
            model_name="itemservicefeessettings",
            name="fee_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=7,
                null=True,
                verbose_name="Fee (percent)",
            ),
        ),
        migrations.AddField(
            model_name="itemservicefeessettings",
            name="fee_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("add", "Add fee to product price"),
                    ("include", "Include fee in product price (no extra line)"),
                ],
                max_length=20,
                null=True,
                verbose_name="Fee mode",
            ),
        ),
    ]
